### ISSUE TITLE
please add a license to your dataset

### ISSUE THREAD

**Issue by danzhang0615** [j-cb/NINCO#1]
Hi,

thanks for releasing this data set, which is very interesting. However, it still misses a license for being usable by others. Could you please add one? Thanks.

**Comment by j-cb** [comment]
Thanks for pointing this out!  
We also published the dataset (same download file) on zenodo under a CC BY 4.0 license. We added links in the readme.  
We now also licensed the code with MIT.

**Comment by danzhang0615** [comment]
> Thanks for pointing this out! We also published the dataset (same download file) on zenodo under a CC BY 4.0 license. We added links in the readme. We now also licensed the code with MIT.

Great. Thanks!
