### ISSUE TITLE
Are NINCO and "popular subsamples" disjoint?

### ISSUE THREAD

**Issue by zjysteven** [j-cb/NINCO#2]
Hi,

A very thorough and solid work! I was wondering if the samples of NINCO and its "popular datasets subsamples" are different and disjoint? For example, do the samples in "popular datasets/Species" also appear in NINCO?

Thanks

**Comment by j-cb** [comment]
Thanks for the kind words!

There are indeed some overlaps between the two datasets, as some of the NINCO classes are based on hand-sorting classes from these popular datasets.

I did a quick search and found the following 8 samples that are in both. It looks to me like this should be all, but my search could have overlooked some.

Sample 37 NINCO_popular_datasets_subsamples/Places/Places_037_f_field_road_00000842.jpg
is also in NINCO as sample 1607 NINCO_OOD_classes/f_field_road/f_field_road_015_00000842.jpg
Sample 38 NINCO_popular_datasets_subsamples/Places/Places_038_f_field_road_00000994.jpg
is also in NINCO as sample 1610 NINCO_OOD_classes/f_field_road/f_field_road_018_00000994.jpg
Sample 39 NINCO_popular_datasets_subsamples/Places/Places_039_f_field_road_00001581.jpg
is also in NINCO as sample 1630 NINCO_OOD_classes/f_field_road/f_field_road_038_00001581.jpg
Sample 40 NINCO_popular_datasets_subsamples/Places/Places_040_f_field_road_00002212.jpg
is also in NINCO as sample 1638 NINCO_OOD_classes/f_field_road/f_field_road_046_00002212.jpg
Sample 50 NINCO_popular_datasets_subsamples/Places/Places_050_f_forest_path_00000583.jpg
is also in NINCO as sample 1696 NINCO_OOD_classes/f_forest_path/f_forest_path_008_00000583.jpg
Sample 51 NINCO_popular_datasets_subsamples/Places/Places_051_f_forest_path_00002066.jpg
is also in NINCO as sample 1733 NINCO_OOD_classes/f_forest_path/f_forest_path_045_00002066.jpg
Sample 114 NINCO_popular_datasets_subsamples/Places/Places_114_s_sky_00003512.jpg
is also in NINCO as sample 3039 NINCO_OOD_classes/s_sky/s_sky_043_00003512.jpg
Sample 679 NINCO_popular_datasets_subsamples/Species/Species_143_sarracenia_alata_12212875.jpg
is also in NINCO as sample 3197 NINCO_OOD_classes/sarracenia_alata/sarracenia_alata_033_12212875.jpg

Best,
Julian

**Comment by zjysteven** [comment]
Awesome. Thanks for the information!
